add-global-variants = true
no-hooks = true
no-tests = true

[psql]
dbname = "sgpdb"
host = "localhost"
user="sgpdb"
pass="ihateducks"
sslmode = "disable"
whitelist = ["reminders"]

[auto-columns]
created = "created_at"
updated = "updated_at"
